title: MadTech
description: A blog about systems, C, assembly and security learning path
baseurl: ""
url: "https://salvador404.github.io"
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme

author:
  name: Salvador404
  email: your@email.com

header_pages:
  - about.md
  - contact.md

highlighter: rouge
markdown: kramdown
