title: MadTech
description: A blog about systems, C, assembly and security learning path
baseurl: ""
url: "https://salvador404.github.io"
theme: jekyll-theme-console

author:
  name: Salvador404
  email: your@email.com

header_pages:
  - about.md
  - contact.md

highlighter: rouge
markdown: kramdown