title: MadTech
description: A blog about systems, C, assembly and security learning path
baseurl: ""
url: "https://salvador404.github.io"
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-remote-theme
  - jekyll-feed  
author:
  name: Salvador404
  email: mad444tech@gmail.com

header_pages:
  -_pages/about.md
  -_pages/contact.md

highlighter: rouge
syntax_highlighter: rouge
markdown: kramdown
